HTTP Web server and gcp
rtrive/f1-telegram-fantasy-bot pull request #29
Opened 2022-06-14 06:50 UTC by rtrive

2022-06-14 06:56 UTC, kin0992 requested changes

2022-06-14 06:56 UTC, kin0992 commented on .github/workflows/ci-cd.yaml
> +  BUCKET: test-riccardo
Is this the right value?

2022-06-14 06:56 UTC, kin0992 commented on src/http_server.py
> +def start():
```suggestion
def start(logger: Logger):
```
and pass the logger to this function from the `main.py` file (as we have done already)

2022-06-14 06:56 UTC, kin0992 commented on src/main.py
> +    http_server_start()
```suggestion
    http_server_start(logger=create_logger(
        name="http-server", level=configuration.log.log_level, format=LOG_FORMAT
    ))
```

2022-06-14 06:56 UTC, kin0992 commented on src/http_server.py
> +HOSTNAME = "localhost"
Should we move these variables to environment variables?

And then create a separate configuration within the `configuration.py`, something like `HttpServerConfiguration`. What do you think?

2022-06-14 07:04 UTC, rtrive commented on .github/workflows/ci-cd.yaml
> +  BUCKET: test-riccardo
yep, but i added others right now

2022-06-16 08:08 UTC, kin0992 commented on src/main.py
> +        log.info(request.response.body)
```suggestion
```

2022-06-16 08:08 UTC, kin0992 commented on src/main.py
> +
After what we have discovered, I'm not sure this is needed

2022-06-16 10:44 UTC, kin0992 approved these changes

2022-06-16 11:17 UTC, merged